### ISSUE TITLE
does not recognize git repository in ~/Library (mac) "Not in a git directory"

### ISSUE THREAD

**Issue by techeddie** [Lil-Dank/lazygit.yazi#6]
hi,
I have a local git repo in `~/Library`. 
With the following mapping I got the message: Not in a git directory
 
```toml
[[manager.prepend_keymap]]
on   = [ "<C-g>" ]
run  = "plugin lazygit"
desc = "run lazygit"
```
When I jump from Yazi to the terminal and run lazygit, I can see the repository.

Any ideas?
